Traceback (most recent call last):
  File "C:\Users\Josue\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Josue\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Josue\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Josue\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Josue\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Josue\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Josue\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd, numpy as np, statsmodels.api as sm, statsmodels.formula.api as smf
import sympy, matplotlib, math, random, networkx
from causalgraphicalmodels import CausalGraphicalModel
from statsmodels.iolib.summary2 import summary_col
import pyreadr
import patsy

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
Cell [1;32mIn[2], line 3[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m[38;5;241m,[39m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m[38;5;241m,[39m [38;5;21;01mstatsmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mapi[39;00m [38;5;28;01mas[39;00m [38;5;21;01msm[39;00m[38;5;241m,[39m [38;5;21;01mstatsmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mformula[39;00m[38;5;21;01m.[39;00m[38;5;21;01mapi[39;00m [38;5;28;01mas[39;00m [38;5;21;01msmf[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01msympy[39;00m[38;5;241m,[39m [38;5;21;01mmatplotlib[39;00m[38;5;241m,[39m [38;5;21;01mmath[39;00m[38;5;241m,[39m [38;5;21;01mrandom[39;00m[38;5;241m,[39m [38;5;21;01mnetworkx[39;00m
[1;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcausalgraphicalmodels[39;00m [38;5;28;01mimport[39;00m CausalGraphicalModel
[0;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mstatsmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01miolib[39;00m[38;5;21;01m.[39;00m[38;5;21;01msummary2[39;00m [38;5;28;01mimport[39;00m summary_col
[0;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mpyreadr[39;00m

File [1;32m~\anaconda3\Lib\site-packages\causalgraphicalmodels\__init__.py:1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcausalgraphicalmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcgm[39;00m [38;5;28;01mimport[39;00m CausalGraphicalModel
[0;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcausalgraphicalmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcsm[39;00m [38;5;28;01mimport[39;00m StructuralCausalModel
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mcausalgraphicalmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mexamples[39;00m [38;5;28;01mas[39;00m [38;5;21;01mexamples[39;00m

File [1;32m~\anaconda3\Lib\site-packages\causalgraphicalmodels\cgm.py:4[0m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mgraphviz[39;00m
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mitertools[39;00m [38;5;28;01mimport[39;00m combinations, chain
[1;32m----> 4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcollections[39;00m [38;5;28;01mimport[39;00m Iterable
[0;32m      7[0m [38;5;28;01mclass[39;00m [38;5;21;01mCausalGraphicalModel[39;00m:
[0;32m      8[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[0;32m      9[0m [38;5;124;03m    Causal Graphical Models[39;00m
[0;32m     10[0m [38;5;124;03m    """[39;00m

[1;31mImportError[0m: cannot import name 'Iterable' from 'collections' (C:\Users\Josue\anaconda3\Lib\collections\__init__.py)

